version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: datajobs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datajobs
    ports:
      - "5432:5432"
    volumes:
      - ../sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
